services:
  mlflow-tracking-server:
    container_name: mlflow-tracking
    image: ghcr.io/mlflow/mlflow
    command: mlflow ui --port 5000 --host 0.0.0.0 --backend-store-uri ./mlruns --artifacts-destination ./mlruns    
    volumes:
      - ./mlruns:/mlruns
    ports:
      - 5000:5000

  default-payment-prediction-service:
    build:
      context: .
      dockerfile: Dockerfile.Service
      tags:
        - default-payment-prediction-service:latest		
        - ghcr.io/marco-marcelo/default-payment-prediction-service:latest
    image: default-payment-prediction-service
    container_name: default-payment-prediction-service
    ports:
      - 5002:5002
