name: Pipeline CI/CD

on:
  push:
    branches: [ testes-ci-cd ]
  pull_request:
    branches: [ testes-ci-cd ]

permissions:
  contents: read
  packages: write

jobs:
  cicd:

    runs-on: ubuntu-latest

    steps:
      - name: Obter repositório
        uses: actions/checkout@v3

      - name: Configurar Docker
        uses: docker/setup-buildx-action@v2

      - name: Iniciar serviços
        run: docker compose up -d

      - name: Criar ambiente para executar testes com o conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: conda.yaml
          activate-environment: OML

      #- name: Executar testes
      #  run: conda run --no-capture-output -n OML pytest

      - name: Iniciar sessão no repositório do GitHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: ligação com o repositório do GitHub
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Construir imagem do serviço
        run: docker build -t ghcr.io/marcomarcelo/default-payment-prediction-service:latest .

      - name: Enviar imagem serviço para o repositório do GitHub
        run: docker push ghcr.io/marcomarcelo/default-payment-prediction-service:latest
