name: Pipeline CI/CD

on:
  push:
    branches: 
      - master
      - testes-ci-cd
  pull_request:
    branches: 
      - master
      - testes-ci-cd

permissions:
  contents: read
  packages: write

jobs:
  cicd:

    runs-on: ubuntu-latest

    steps:
      - name: Obter repositório
        uses: actions/checkout@v3

      - name: Configurar Docker
        uses: docker/setup-buildx-action@v2

      - name: Iniciar serviços
        run: docker compose up -d

      - name: Verificar containers em execução
        run: docker ps

      - name: Criar ambiente para executar testes com o conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: conda.yaml
          activate-environment: OML

      - name: Verificar containers em execução
        run: docker ps

      - name: Ver logs do serviço
        run: docker compose logs default-payment-prediction-service       
           
      #- name: Executar testes
      #  run: conda run --no-capture-output -n OML pytest

      - name: Iniciar sessão no repositório do GitHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          #password: ${{ secrets.PAT }}

      - name: Enviar imagem serviço para o repositório do GitHub
        run: docker push ghcr.io/marcomarcelo/default-payment-prediction-service:latest